# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('driver', '0002_auto_20180830_1745'),
        ('sacco', '0002_auto_20180830_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg', models.CharField(max_length=200)),
                ('car_type', models.CharField(choices=[('BUS', 'BUS'), ('NISSAN', 'NISSAN')], max_length=200)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver')),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco')),
            ],
        ),
    ]
