# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vihecle', '0002_auto_20180901_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='car_reg',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.Driver'),
        ),
    ]
