# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='id_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='lname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='tel_number',
            field=models.IntegerField(null=True),
        ),
    ]
