# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-30 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('lname', models.CharField(max_length=200)),
                ('id_number', models.IntegerField()),
                ('tel_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('title', models.CharField(choices=[('chairman', 'chairman'), ('vice chairman', 'v_chairman'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Office Manager', 'Office_Manager'), ('Office Clerk', 'Office_Clerk'), ('Route Inspector', 'Route_Inspector')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contacts', models.CharField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco'),
        ),
        migrations.AddField(
            model_name='official',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco'),
        ),
    ]
