# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-10 19:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('id_number', models.CharField(max_length=200, null=True, unique=True)),
                ('tel_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200, null=True)),
                ('license_no', models.CharField(max_length=200)),
                ('status', models.CharField(default=False, max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Official',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200, null=True)),
                ('lname', models.CharField(max_length=200, null=True)),
                ('id_number', models.CharField(max_length=200, null=True, unique=True)),
                ('tel_number', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200, null=True)),
                ('title', models.CharField(choices=[('chairman', 'chairman'), ('vice chairman', 'v_chairman'), ('Treasurer', 'Treasurer'), ('Secretary', 'Secretary'), ('Office Manager', 'Office_Manager'), ('Office Clerk', 'Office_Clerk'), ('Route Inspector', 'Route_Inspector')], max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=200)),
                ('route_number', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sacco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('tel_number', models.CharField(max_length=400, null=True)),
                ('email', models.CharField(max_length=400)),
                ('sacco_no', models.CharField(max_length=200, unique=True)),
                ('postal_address', models.CharField(max_length=400)),
                ('postal_code', models.CharField(max_length=400)),
                ('town', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg', models.CharField(max_length=200, unique=True)),
                ('car_type', models.CharField(choices=[('BUS', 'BUS'), ('NISSAN', 'NISSAN')], max_length=200)),
                ('sacco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco'),
        ),
        migrations.AddField(
            model_name='official',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Sacco'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sacco.Vehicle'),
        ),
    ]
