# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='no_raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='no_raters',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default=False, max_length=200, null=True),
        ),
    ]
