# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sacco', '0002_auto_20180912_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='sacco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_sacco', to='sacco.Sacco'),
        ),
    ]
